[package]
name = "fasing"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1.0.147"
serde = { version = "1.0.228", features = ["derive"] }

euclid = { version = "0.22.11", features = ["serde"] }
anyhow = "1.0.100"

[build-dependencies]
serde_json = "1.0.145"
anyhow = "1.0.100"